#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$logger = new \Phambda\Logger\NanoLogger();
$runtime = new \Phambda\Http\Runtime(
    new \Phambda\Example\Http\ExampleHandler($logger),
    $logger,
);
$runtime->run();
